name: Build and Release GeyserPreventServerSwitch

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: 16
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle shadowJar
        run: ./gradlew clean shadowJar --no-daemon

      - name: Upload artifact (CI only)
        if: github.ref_type != 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: GeyserPreventServerSwitch
          path: build/libs/GeyserPreventServerSwitch*.jar

      - name: Create GitHub Release and upload jars (on tag)
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/GeyserPreventServerSwitch*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
